### PR TITLE
Migrate pep8 to pycodestyle

### PR DESCRIPTION
**Pull request by Surgo**
pep8 was renamed to [pycodestyle](https://github.com/PyCQA/pycodestyle)

### CODE REVIEW

**Comment by alexntt** [comment]
Our builds are breaking due to this now (I think):

```
flake8 installed: DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6,argparse==1.4.0,flake8==2.6.0,flake8-blind-except==0.1.0,importlib==1.0.3,iso8601==0.1.11,mccabe==0.5.0,ntteam.commons==0.4a1466500042,ordereddict==1.1,pep8-naming==0.3.3,pycodestyle==2.0.0,pyflakes==1.2.3,requests==2.10.0,six==1.10.0
flake8 runtests: PYTHONHASHSEED='1372244244'
flake8 runtests: commands[0] | flake8 na_commons
Traceback (most recent call last):
  File "../../../bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/jenkins/workspace/ntteam-commons-flake8/.tox/flake8/lib/python2.6/site-packages/flake8/main.py", line 28, in main
    flake8_style = get_style_guide(parse_argv=True)
  File "/home/jenkins/workspace/ntteam-commons-flake8/.tox/flake8/lib/python2.6/site-packages/flake8/engine.py", line 233, in get_style_guide
    kwargs['parser'], options_hooks = get_parser()
  File "/home/jenkins/workspace/ntteam-commons-flake8/.tox/flake8/lib/python2.6/site-packages/flake8/engine.py", line 74, in get_parser
    (extensions, parser_hooks, options_hooks, ignored) = _register_extensions()
  File "/home/jenkins/workspace/ntteam-commons-flake8/.tox/flake8/lib/python2.6/site-packages/flake8/engine.py", line 58, in _register_extensions
    checker = _load_entry_point(entry, verify_requirements=False)
  File "/home/jenkins/workspace/ntteam-commons-flake8/.tox/flake8/lib/python2.6/site-packages/flake8/engine.py", line 37, in _load_entry_point
    plugin = entry_point.resolve()
  File "/home/jenkins/workspace/ntteam-commons-flake8/.tox/flake8/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jenkins/workspace/ntteam-commons-flake8/.tox/flake8/lib/python2.6/site-packages/flake8_blind_except.py", line 1, in <module>
    import pep8
ImportError: No module named pep8
```

I think this was caused by updating flake8==2.5.4 to 2.6.0.

**Comment by Surgo** [comment]
And flake>=2.6.0 depends on pycodestyle

https://github.com/PyCQA/flake8/blob/2.6.0/setup.py#L53

**Comment by Surgo** [comment]
@elijahandrews ping

**Comment by elijahandrews** [comment]
Hey there, sorry I missed this before, I was out of town. Thanks for the change! Will merge.

**Comment by elijahandrews** [comment]
Merged and released in version 0.1.1

**Comment by Surgo** [comment]
thank you :)

**Pull request merged**
